version: "3"

services:


  microservizio-task:

    build: ./fixmi-microservizio-task

    ports:
      - "3004:3002"
      - "3003:3001"

    volumes:
      - ./fixmi-microservizio-task:/app

    restart: always

    networks:
      fixmi-network:
        ipv4_address: ${MICROSERVIZIO_TASK_IP}


  microservizio-autenticazione:

    build: ./fixmi-microservizio-autenticazione

    ports:
      - "3002:3002"
      - "3001:3001"

    volumes:
      - ./fixmi-microservizio-autenticazione:/app

    restart: always

    networks:
      fixmi-network:
        ipv4_address: ${MICROSERVIZIO_AUTENTICAZIONE_IP}


  micriservizio-database:

    container_name: "fiixmidb"
    image: mongo:5.0.8-focal
    restart: always

    ports:
      - 27017:27017

    networks:
      fixmi-network:
        ipv4_address: ${MICROSERVIZIO_DB_IP}

    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d  # Mount init script directory
      - ./db:/data/db                               # Use this to persist data
                                                    # outside of the container

    environment:
      MONGO_INITDB_ROOT_USERNAME: fixme
      MONGO_INITDB_ROOT_PASSWORD: fixme

    # listen to all ips, enable authentication
    command: ["mongod", "--bind_ip_all", "--auth"]


  fixmi-api-gateway:

    build: ./fixmi-api-gateway

    ports:
      - "7777:7777"

    volumes:
      - ./fixmi-api-gateway/nginx.conf:/etc/nginx/nginx.conf

    tty: true

networks:
  fixmi-network:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IP}

