version: "3"

services:
  microservizio-task:
    build: ./fixmi-microservizio-task
    ports:
      - "3004:3002"
      - "3003:3001"
    volumes:
      - ./fixmi-microservizio-task:/app
    restart: always

  microservizio-autenticazione:
    build: ./fixmi-microservizio-task
    ports:
      - "3002:3002"
      - "3001:3001"
    volumes:
      - ./fixmi-microservizio-task:/app
    restart: always

#   micriservizio-database:
#      build: ./microservizio-database
