version: "3"

services:


  microservizio-task:

    build: ./fixmi-microservizio-task

    ports:
      - "3004:3002"
      - "3003:3001"

    volumes:
      - ./fixmi-microservizio-task:/app

    restart: always

    environment:
      MICROSERVIZIO_DB_IP: ${MICROSERVIZIO_DB_IP}
      MICROSERVIZIO_DB_USERNAME: ${DB_USERNAME}
      MICROSERVIZIO_DB_PASSWORD: ${DB_PASSWORD}
      MICROSERVIZIO_AUTENTICAZIONE_IP: ${MICROSERVIZIO_AUTENTICAZIONE_IP}

    networks:
      fixmi-network:
        ipv4_address: ${MICROSERVIZIO_TASK_IP}


  microservizio-autenticazione:

    build: ./fixmi-microservizio-autenticazione

    ports:
      - "3002:3002"
      - "3001:3001"

    volumes:
      - ./fixmi-microservizio-autenticazione:/app

    restart: always

    environment:
      MICROSERVIZIO_DB_IP: ${MICROSERVIZIO_DB_IP}
      MICROSERVIZIO_DB_USERNAME: ${DB_USERNAME}
      MICROSERVIZIO_DB_PASSWORD: ${DB_PASSWORD}
      MICROSERVIZIO_AUTENTICAZIONE_IP: ${MICROSERVIZIO_AUTENTICAZIONE_IP}

    networks:
      fixmi-network:
        ipv4_address: ${MICROSERVIZIO_AUTENTICAZIONE_IP}



  microservizio-home:

    build: ./fixmi-microservizio-home

    ports:
      - "3006:3002"
      - "3005:3001"

    volumes:
      - ./fixmi-microservizio-home:/app

    restart: always

    environment:
      MICROSERVIZIO_DB_IP: ${MICROSERVIZIO_DB_IP}
      MICROSERVIZIO_DB_USERNAME: ${DB_USERNAME}
      MICROSERVIZIO_DB_PASSWORD: ${DB_PASSWORD}
      MICROSERVIZIO_AUTENTICAZIONE_IP: ${MICROSERVIZIO_AUTENTICAZIONE_IP}

    networks:
      fixmi-network:
        ipv4_address: ${MICROSERVIZIO_HOME_IP}


  micriservizio-database:

    container_name: "fixmidb"
    image: mongo:5.0.8-focal
    restart: always

    ports:
      - 27017:27017

    networks:
      fixmi-network:
        ipv4_address: ${MICROSERVIZIO_DB_IP}

    volumes:
      - ./init_scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js  # Mount init script
      - ./db:/data/db                               # Use this to persist data
                                                    # outside of the container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

    # listen to all ips, enable authentication
    command: ["mongod", "--bind_ip_all", "--auth"]


  fixmi-api-gateway:

    build: ./fixmi-api-gateway

    ports:
      - "7777:7777"

    volumes:
      - ./fixmi-api-gateway/nginx.conf:/etc/nginx/nginx.conf

    tty: true

networks:
  fixmi-network:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IP}

